#!/bin/bash

echo ""
echo "Updating apt ..."
sudo apt update -q -y
echo ""
echo "Installing mc ..."
sudo apt install -q mc -y 1>/dev/null
echo ""
echo "Installing lnav ..."
sudo apt install -q lnav -y 1>/dev/null

echo ""
echo "Install gmd ..."
curl -sS -L --create-dirs -o ~/gmd/gmd "https://github.com/michael-reichenauer/gmd/releases/latest/download/gmd_linux" && chmod +x ~/gmd/gmd
echo 'export PATH=$PATH:~/gmd' >>~/.profile
. ~/.profile
echo "gmd version: $(gmd --version)"

echo ""
echo "Install git post commit hook ..."
cp ./gmd/tools/post-commit-sample ./.git/hooks/post-commit
chmod +x ./.git/hooks/post-commit

echo ""
echo "Done"

