name: Build and release

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build_test_release_job:
    runs-on: ubuntu-latest
    name: Build, Test and Release Job

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Update .env and manifest file with current build time and git sha id to support
      # version handling of the web site to automatically upgrade to latest version faster
      - name: Update git sha and build time
        shell: bash
        run: |
          BUILD_TIME="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          echo Build $BUILD_TIME ${{github.sha}}
          sed -i "s/BUILD_TIME/$BUILD_TIME/g" gmd/Build.cs
          sed -i "s/BUILD_SHA/${{github.sha}}/g" gmd/Build.cs
          git log -3 --format=full

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Build & Test
        id: build
        run: |
          echo Build on branch: ${{ github.ref }}
          ./build
          echo "version=$(./gmd_linux --version)" >> $GITHUB_OUTPUT
          echo Version: $(./gmd_linux --version)
          echo "isRelease=${{ github.ref == 'refs/heads/main' }}" >> $GITHUB_OUTPUT
          echo "isPreRelease=${{ github.ref == 'refs/heads/dev' }}" >> $GITHUB_OUTPUT
          echo "isPublish=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        if: steps.build.outputs.isPublish == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.build.outputs.version }}
          release_name: Version ${{ steps.build.outputs.version }}
          draft: false
          prerelease: ${{steps.build.outputs.isPreRelease == 'true'}}
          body: ${{ github.event.head_commit.message }} </br>[Change log](https://github.com/michael-reichenauer/gmd/blob/main/CHANGELOG.md)

      - name: Upload Linux artifact
        if: steps.build.outputs.isPublish == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gmd_linux
          asset_name: gmd_linux
          asset_content_type: application/octet-stream

      - name: Upload Windows artifact
        if: steps.build.outputs.isPublish == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gmd_windows
          asset_name: gmd_windows
          asset_content_type: application/octet-stream

      - name: Upload OSX/Mac artifact
        if: steps.build.outputs.isPublish == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gmd_osx
          asset_name: gmd_osx
          asset_content_type: application/octet-stream

      - name: Upload OSX/Mac artifact (legacy)
        if: steps.build.outputs.isPublish == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gmd_osx
          asset_name: gmd_mac
          asset_content_type: application/octet-stream

      - name: Upload Windows setup file
        if: steps.build.outputs.isPublish == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gmd/Installation/installer/gmdSetup.exe
          asset_name: gmdSetup.exe
          asset_content_type: application/octet-stream

      # - name: Upload Windows artifact (gmd.exe zipped)
      #   if: steps.check-branch.outputs.isRelease == 'true'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./gmd.zip
      #     asset_name: gmd.zip
      #     asset_content_type: application/octet-stream

      # - name: Upload Windows artifact (old name)
      #   if: steps.check-branch.outputs.isRelease == 'true'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./gmd_windows
      #     asset_name: gmd.exe
      #     asset_content_type: application/octet-stream
